# Generated by Django 5.1 on 2024-12-04 14:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Venta',
            fields=[
                ('id_venta', models.CharField(max_length=6, primary_key=True, serialize=False)),
                ('id_cliente', models.PositiveIntegerField()),
                ('id_empleado', models.PositiveIntegerField()),
                ('id_producto', models.PositiveIntegerField()),
                ('fecha_venta', models.DateField(verbose_name='')),
                ('cant', models.IntegerField()),
                ('importe_pagar', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
        ),
    ]
